---
title: "Mid-January Working Meeting (1/18/2018)"
output: html_document 
---

The major goals of this meeting are just to get Fred/Nate acquainted with the proposed workflow, the model structure, and to develop a plan to move forward. 

### Resources for meeting (1/17/2018)
1. SESYNC Tutorials ([click here](http://cyberhelp.sesync.org/basic-R-lesson/2017/07/18/#/slides/plot) and [here](http://cyberhelp.sesync.org/basic-R-lesson/2017/07/18/#/slides/plot))
2. Introduction to RStudio and GIT ([click here](http://r-pkgs.had.co.nz/git.html))
3. R Markdown Tutorial ([click here](http://r-pkgs.had.co.nz/git.html))

### Goals for Meeting:
1. Familiarize Fred with SESYNC cyber infrastructure, GitHub, and WHC Model.
2. Discuss steps forward
3. Develop plan/deliverables for next week  (For example: Run initial PPR model)

### Meeting Summary and Action Items (for next time):
We walked through SESYNC cyber infrastructure and initial code.  Action items include:

1. Nate needs to migrate the model to github. 
2. Once Nate completes (1), Fred will demo the model. 
3. In an effort to use time most efficiently, we won’t meet with Nandita/Daniel next week (1/24). Instead, Nate/Fred will use the time to discuss the model. 
4. However, we will work to have an updated model (e.g., Nate will address known bugs) and have applied it to PPR (Fred) for the next scheduled meeting with Nandita/Daniel (Jan 31).  
